### ISSUE TITLE
Add mock data capabilities to project

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#32]
In order to quickly set up a demonstration of the platform, it would be useful to generate mock data. Add a mock data package to the project and set up some initial mock data scripts to populate project collections.
# Criteria
- [ ] Mock data package exists in project
- [ ] Mock data scripts added to project
  - [ ] Create home groups (e.g. 3 home groups created)
  - [ ] Create homes (e.g. 3-5 homes per home group)
  - [ ] Create residents (e.g. 6-12 residents per home)
  - [ ] Create activities (e.g. 20-50 activities per resident over last 30 days)
# Resources
- [Generate Fake Data for Your JavaScript Applications Using Faker](https://scotch.io/tutorials/generate-fake-data-for-your-javascript-applications-using-faker)
- [faker.js](https://github.com/Marak/faker.js)

**Comment by brylie** [comment]
@ErikPel this task would also be useful for testing, demonstration, and documentation purposes.

**Comment by ErikPel** [comment]
Started working on this since I need to put stuff into my database anyway for the screenshots.

For homes is it okay if I use the fakerjs city name function or do we need something more specific for the home name mock data?
What kind of home group names should I be creating?

My activity array that I take one at random looks like this
`var activities = ["Story time", "Musical events", "Board games and cards", "Food-centered activities", "Exercises", "Stretching/resistence training", "Sensory stimulation", "Pet therapy", "Gardening", "Sewing", "Rug hooking", "Finger painting", "Painting", "Knitting and crocheting", "Leather crafts"]
`
which I took from googling "nursing home activities" and then scraping all the headers,
Is that okay?

**Comment by brylie** [comment]
Home names and group names can be any string. I.e. they are generally 'nicknames' that reference the home or group in conversation. E.g. a manager could direct a volunteer to 'Home A'.

**Comment by brylie** [comment]
That looks like a good activity list. It could even be shortened to around 7 activity categories, so that visualizations do not have too many colors.

**Comment by ErikPel** [comment]
https://github.com/ErikPel/wellbeing-mock-data

Any thoughts?

**Comment by brylie** [comment]
Looks great! Please open a pull request, and I will add a couple of suggestions.

**Comment by ErikPel** [comment]
What kind of folder structure are we talking here? I'm currently using packages folder in the project root.

**Comment by brylie** [comment]
Lets stick with your `packages` directory approach for now.
