### ISSUE TITLE
Users added to all groups not able to see all groups on Homes page

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#420]
It was reported that a non-admin user who has been assigned to all groups is not able to see all of the groups listed on the Homes page.

## Task
Ensure that users can see all groups to which they are assigned on the Homes page, particularly in the case where the user is assigned to many/all homes.

**Comment by PayalChoksey17** [comment]
@brylie  This issue is non-reproducible.
**Scenario 1 :** Add 5 groups  to non-admin and logged in to non-admin. All 5 Groups are displays on Homes Page for non-admin account.

**Scenario 2:** Add all groups ( 22 groups ) to non-admin account and logged in to non-admin. All 22 groups are displayed on Home page for non-admin account.

Video : https://www.loom.com/share/51d3eab1ba754721b1263696ac090c60
Repo Rate : 0/5

**Comment by brylie** [comment]
OK. I will try to find out what is the cause, or if it is verifiable, on the production system.
